'use client';

import { useState, useEffect } from 'react';
import { BellIcon, Cross2Icon, CheckIcon } from '@radix-ui/react-icons';

interface PulseItem {
  id: string;
  title: string;
  message: string;
  urgency: 'critical' | 'high' | 'medium' | 'low';
  category: 'alert' | 'warning' | 'info';
  timestamp: string;
  done?: boolean;
}

interface PulseOrbProps {
  enabled?: boolean;
}

/**
 * PulseOrb - AI-powered insights and notifications
 *
 * Displays urgent operational insights generated by AI:
 * - Critical alerts (resource constraints, delivery risks)
 * - Warnings (capacity issues, deadline conflicts)
 * - Info (opportunities, recommendations)
 *
 * Position: Bottom-left (position 2)
 */
export function PulseOrb({ enabled = true }: PulseOrbProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [pulseItems, setPulseItems] = useState<PulseItem[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isOffline, setIsOffline] = useState(false);

  useEffect(() => {
    if (!enabled) return;
    fetchPulse();

    // Auto-refresh every 5 minutes
    const interval = setInterval(fetchPulse, 5 * 60 * 1000);
    return () => clearInterval(interval);
  }, [enabled]);

  const fetchPulse = async () => {
    setIsLoading(true);
    setIsOffline(false);

    try {
      const response = await fetch('/api/ai/pulse?tenantId=ppg-main');
      if (!response.ok) throw new Error('Failed to fetch pulse');

      const data = await response.json();
      setPulseItems(data.items || []);
    } catch (error) {
      console.error('Pulse fetch error:', error);
      setIsOffline(true);
      // Use mock data when offline
      setPulseItems(getMockPulseItems());
    } finally {
      setIsLoading(false);
    }
  };

  const markDone = (id: string) => {
    setPulseItems((prev) =>
      prev.map((item) => (item.id === id ? { ...item, done: true } : item))
    );
  };

  const dismiss = (id: string) => {
    setPulseItems((prev) => prev.filter((item) => item.id !== id));
  };

  const activeItems = pulseItems.filter((item) => !item.done);
  const activeCount = activeItems.length;

  if (!enabled) return null;

  const getUrgencyColor = (urgency: string) => {
    switch (urgency) {
      case 'critical':
        return 'border-red-500 bg-red-50 dark:bg-red-950';
      case 'high':
        return 'border-orange-500 bg-orange-50 dark:bg-orange-950';
      case 'medium':
        return 'border-yellow-500 bg-yellow-50 dark:bg-yellow-950';
      default:
        return 'border-blue-500 bg-blue-50 dark:bg-blue-950';
    }
  };

  return (
    <>
      {/* Orb Button */}
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="fixed bottom-4 left-20 z-40 w-14 h-14 rounded-full shadow-lg hover:scale-110 transition-transform flex items-center justify-center text-white"
        style={{
          background: 'linear-gradient(135deg, #a855f7, #ec4899)',
        }}
        title="AI Pulse - Operational Insights"
      >
        <BellIcon className="w-6 h-6" />
        {activeCount > 0 && (
          <span className="absolute -top-1 -right-1 w-6 h-6 bg-red-500 rounded-full flex items-center justify-center text-xs font-bold">
            {activeCount}
          </span>
        )}
      </button>

      {/* Panel */}
      {isOpen && (
        <div className="fixed bottom-20 left-20 z-50 w-96 bg-white dark:bg-gray-900 rounded-lg shadow-2xl border border-gray-200 dark:border-gray-700 max-h-[500px] flex flex-col">
          {/* Header */}
          <div className="px-4 py-3 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <h3 className="font-bold text-gray-900 dark:text-gray-100">AI Pulse</h3>
              {isOffline && (
                <span className="text-xs text-yellow-600 dark:text-yellow-400">(Offline Mode)</span>
              )}
            </div>
            <button
              onClick={() => setIsOpen(false)}
              className="p-1 hover:bg-gray-100 dark:hover:bg-gray-800 rounded"
            >
              <Cross2Icon className="w-4 h-4" />
            </button>
          </div>

          {/* Content */}
          <div className="flex-1 overflow-y-auto p-4 space-y-3">
            {isLoading && pulseItems.length === 0 ? (
              <div className="text-center text-gray-500 py-8">Loading insights...</div>
            ) : activeItems.length === 0 ? (
              <div className="text-center text-gray-500 py-8">
                <BellIcon className="w-12 h-12 mx-auto mb-2 opacity-50" />
                <p>No active insights</p>
                <p className="text-xs mt-1">All caught up! 🎉</p>
              </div>
            ) : (
              activeItems.map((item) => (
                <div
                  key={item.id}
                  className={`p-3 rounded-lg border-l-4 ${getUrgencyColor(item.urgency)}`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex-1">
                      <h4 className="font-semibold text-sm text-gray-900 dark:text-gray-100">
                        {item.title}
                      </h4>
                      <p className="text-xs text-gray-600 dark:text-gray-400 mt-1">
                        {item.message}
                      </p>
                      <p className="text-xs text-gray-400 dark:text-gray-500 mt-2">
                        {new Date(item.timestamp).toLocaleTimeString()}
                      </p>
                    </div>
                    <div className="flex gap-1">
                      <button
                        onClick={() => markDone(item.id)}
                        className="p-1 hover:bg-white dark:hover:bg-gray-800 rounded"
                        title="Mark as done"
                      >
                        <CheckIcon className="w-4 h-4 text-green-600" />
                      </button>
                      <button
                        onClick={() => dismiss(item.id)}
                        className="p-1 hover:bg-white dark:hover:bg-gray-800 rounded"
                        title="Dismiss"
                      >
                        <Cross2Icon className="w-4 h-4 text-gray-500" />
                      </button>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>

          {/* Footer */}
          <div className="px-4 py-2 border-t border-gray-200 dark:border-gray-700 text-xs text-gray-500 text-center">
            Auto-refreshes every 5 minutes
          </div>
        </div>
      )}
    </>
  );
}

// Mock data for offline mode
function getMockPulseItems(): PulseItem[] {
  return [
    {
      id: '1',
      title: 'High Utilization Alert',
      message: 'Senior consultants at 95% capacity this week. Consider resource reallocation.',
      urgency: 'critical',
      category: 'alert',
      timestamp: new Date().toISOString(),
    },
    {
      id: '2',
      title: 'Engagement Milestone Due',
      message: 'Phoenix Foundation deliverable due in 2 days. Review progress.',
      urgency: 'high',
      category: 'warning',
      timestamp: new Date().toISOString(),
    },
    {
      id: '3',
      title: 'Revenue Opportunity',
      message: 'Client satisfaction score increased. Good time for upsell discussion.',
      urgency: 'low',
      category: 'info',
      timestamp: new Date().toISOString(),
    },
  ];
}
